### PR TITLE
sign error

### PR DESCRIPTION
**Pull request by ddkohler**
Tested code with non-zero resonance frequency; Found anti-resonant conditions with Hamiltonians.
Electric field pulse signs mirror the signs of the hamiltonians (i.e. we currently simulate w_ag + w_laser)

cf. Kohler 2017 Eqns. S9-14

### CODE REVIEW

**Comment by darienmorrow** [comment]
@ksunden is this ready?

**Comment by ksunden** [comment]
I still want to check the CUDA code (manually) and have not taken the time to do so...

@darienmorrow Is there a timeline that you would like this merged for?

**Comment by darienmorrow** [comment]
@ksunden can it be done by 2020-05-01?

**Comment by ksunden** [comment]
@darienmorrow I think that works, I'll plan on attackin it later this week

**Comment by ksunden** [comment]
I am satisfied, just made some changes to target.py so that it runs and produces a graph, as that is more useful than what it was... Do think we should spend some time making proper examples/docs at some point... but _right_ now is not the time, at least for me.

**Pull request merged**
