### PR TITLE
[WIP] scan

### PR DESCRIPTION
**Pull request by untzag**

### CODE REVIEW

**Comment by ksunden** [comment]
We're going to have to do a bit of git trickery to get this to work, not to much, I hope, but may be a little annoying. I will take point on doing this, but want to do so when others are nearby to help me sort out what all needs to be included.

Basically, we are going to have to rebase and replay the commits we want out of this on top of the current master branch.
(I'm wishing I hadn't squashed and merged, that would have made this particular step easier)

**Comment by untzag** [comment]
gosh :worried: 

happy to help, just let me know where and when

**Comment by ksunden** [comment]
If I'm reading this correctly, this only has one commit which needs to be cherry picked and rebased on current HEAD, that is dec7766, the last commit. All other commits were merged as #19

**Comment by ksunden** [comment]
Superseded by #36

**Pull request closed without merging**
